<a href="https://colab.research.google.com/github/SaRINx55/tutorials_ml/blob/master/TorchTutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

1.1.0


In [0]:
import numpy as np

In [21]:
listx=([1,2],[2,3],[3,4])
es_tensor = torch.tensor(listx)
es_tensor


tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [22]:
np_tensor = torch.tensor(np.array([1,2,3,4,5,6,7,8,9]))
np_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(np.tensor)

torch.Tensor

In [0]:
#assign datatype to tensor -dtype
tensor_float=torch.tensor([1,2,3,4,5,6], dtype=torch.float32)

In [13]:
tensor_float


tensor([1., 2., 3., 4., 5., 6.])

In [0]:
#important parameters in torch---> Device & Requires_grad to be done later

In [15]:
torch.arange(1,100,0.01)

tensor([ 1.0000,  1.0100,  1.0200,  ..., 99.9700, 99.9800, 99.9900])

In [18]:
#identity matrix creation
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [19]:
torch.full((2,3),0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])